### ISSUE TITLE
Add support for resources requests and limits

### ISSUE THREAD

**Issue by AlexisColes** [actions/runner-container-hooks#100]
The actions runner controller allows me to run a bunch of github agents waiting for container jobs in k8.
As these agents don't really do anything it would be good if I could keep a whole bunch of these agents running ready to pick up jobs as and when required with minimal resource requests.

```
resources:
        requests:
          cpu: 5m
          memory: 150Mi
```

I would then like the container jobs to define the amount of resources they want for each container and for this information to be passed through to the container spec.

```
jobs:
  container-test-job:
    runs-on: my-container-waiter
    container:
      image: node:14.16
      resources:
         requests:
           cpu: 500m
           memory: 2Gi
    services:
      postgres:
        image: postgres
         resources:
           requests:
             cpu: 500m
             memory: 2Gi
```
This would be very useful as we would not have to keep warm compute running for all the different permutations of required resources for out jobs and could just keep an amount of warm low priority compute to be share by all the different jobs.

Unfortunately there is no resources property for either a container or a service but maybe we can supply this information via the env property, something like.
```
jobs:
  container-test-job:
    runs-on: my-container-waiter
    container:
      image: node:14.16
      env:
         k8_resource_request_cpu:  500m
         k8_resource_request_memory: 2Gi
    services:
      postgres:
        image: postgres
        env:
           k8_resource_request_cpu:  500m
           k8_resource_request_memory: 2Gi
```

**Comment by nikola-jokic** [comment]
Hey @AlexisColes,

Thank you for submitting this issue so clearly! There is an [ongoing work](https://github.com/actions/runner-container-hooks/pull/96) right now to allow merges and customization of container specs. But based on your description, I can see that it can't fit all cases well, especially for different workflows requiring different sets of limits and requests based on containers it needs to spin up.

Right now, I would prefer the env approach. It would eliminate changes in the workflow yaml file, but can carry a special meaning to the hook. I will bring this up to the team, but it seems like a great suggestion to me

**Comment by nikola-jokic** [comment]
Hey, closing this issue since it has been fixed with 0.4.0 release allowing definition overrides :relaxed:

**Comment by jmccarty3** [comment]
@nikola-jokic I'm not sure how the overrides that were introduced in 0.4.0 (and refined in later versions) fixes this specific issue. The template overrides that can be provided for containers are great for static mutations like imagePullSecrets, sidecars, volumets, etc. 

The overrides however do not allow for dynamic resource setting as originally proposed in the issue. Static resources could be added with the $job entry but that would only allow a user to provide every job container with the same resource requests/limits. If pulling information from the container env variables is not ideal, it would be a nice middle ground to have the job resource request/limits set from reading the `--cpus` and `--memory` options from the `jobs.*.container.options`.

I think this issue should be reopend until proper support is in place or is stated as not going to be supported.

**Comment by jasonwbarnett** [comment]
Here is my rough plan to address this:

1. Update the actions-runner-controller to add a new label [here][2] to the ephemeral runner pod, i.e. 

   ```golang
          labels["ephemeral-runner-name"] = runner.ObjectMeta.Name
   ```

2. Update the runner-container-hooks to dynamically add podAffinity using the label selector matching the ephemeral runner name

   With this change plus setting `ACTIONS_RUNNER_USE_KUBE_SCHEDULER` to `true`, this *should* guarantee the the pod is spun up on the same node as the ephemeral runner pod.

3. Lastly, I think I can modify runner-container-hooks to pull out a nested YAML structure from [jobs.<job_id>.container.options][1] and apply it to the -workflow pod spec allowing for dynamic cpu and memory requests.

   ```yaml
   name: CI
   on:
     push:
       branches: [ main ]
   jobs:
     container-test-job:
       runs-on: ubuntu-latest
       container:
         image: node:18
         options: |
           resources:
             requests:
               memory: "64Mi"
               cpu: "250m"
             limits:
               memory: "128Mi"
               cpu: "500m"
       steps:
         - name: Check for dockerenv file
           run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
   ```

Ideally the [jobs.<job_id>.container](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idcontainer) spec would be extended with a new key, but without that I could hack the existing schema and make it all work.

Any others thoughts?

[1]: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idcontaineroptions
[2]: https://github.com/actions/actions-runner-controller/blob/gha-runner-scale-set-0.10.1/controllers/actions.github.com/resourcebuilder.go#L577-L643
