### ISSUE TITLE
ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE warns about container name

### ISSUE THREAD

**Issue by wasd171** [actions/runner-container-hooks#116]
Hello!

I am using `ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE` with the following content (mildly redacted):

```
apiVersion: v1
kind: PodTemplate
metadata:
  annotations:
    karpenter.sh/do-not-evict: "true"
spec:
  serviceAccountName: xxx-arc-runners-sa
  securityContext:
    fsGroup: 123
  containers:
    - name: "$job"
      resources:
        requests:
          memory: 4Gi
          cpu: 1
```

It gets applied successfully, but on every run I am getting this: `Warning: Skipping name override: name can't be overwritten`

I am using `$job` as a container name, so I would expect to see no warning
