### ISSUE TITLE
containerMode: kubernetes: `Command.RunScriptStep` in `packages/k8s/src/index.ts` never returns

### ISSUE THREAD

**Issue by bjoto** [actions/runner-container-hooks#124]
I'm running ARC in containerMode: kubernetes, and for some workflow steps, the step never completes.

This is deployed on GKE (Google K8s Engine) with Autopilot.

Workflow:
```
name: linux-riscv-ci-patches

defaults:
  run:
    shell: bash -leo pipefail {0}

on: push

jobs:
  build-patches:
    runs-on: arc-runner-set-2
    timeout-minutes: 50400 # 35 days
    container:
      image: ghcr.io/linux-riscv/pw-runner-multi:latest
    steps:
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
      - name: Checkout git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - run: pwd
      - run: ls -l
      - name: Run checks
        run: |
          bash .github/scripts/patches.sh |& tee /build/run.log
```

The last `Run checks` step never completes. I've done a build of the Runner that has additional logging, and I can verify that `Command.RunScriptStep` in `packages/k8s/src/index.ts` never completes -- i.e. the hook script `/home/runner/k8s/index.js` never returns.

When I exec into the workflow container, I can verify that the script has completed, and is not running any more.

The `Run check` step takes ~1h to complete.

Expected:
* The packages/k8s/src/index.ts should complete, when the exec script is done.

Helm setup:
```
githubConfigUrl: "https://github.com/bjoto/linux"
githubConfigSecret:
  github_token: "REDACTED"

maxRunners: 10
minRunners: 0

containerMode:
  type: "kubernetes"

template:
  spec:
    securityContext:
      fsGroup: 123
    containers:
      - name: runner
        image: ghcr.io/linux-riscv/runner-multi:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
            value: "/home/runner/config/worker-podspec.yaml"
          - name: ACTIONS_RUNNER_USE_KUBE_SCHEDULER
            value: "true"
          - name: ACTIONS_STEP_DEBUG
            value: "true"
          - name: ACTIONS_RUNNER_DEBUG
            value: "true"
          - name: RUNNER_DEBUG
            value: "1"
        volumeMounts:
          - name: worker-podspec-volume
            mountPath: /home/runner/config
            readOnly: true
    volumes:
      - name: worker-podspec-volume
        configMap:
          name: worker-cm
          items:
            - key: worker-podspec.yaml
              path: worker-podspec.yaml
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              storageClassName: "premium-rwx"
              accessModes: [ "ReadWriteMany" ]
              resources:
                requests:
                  storage: 100Gi
```
