### ISSUE TITLE
containerMode Kubernetes: new pods get ErrImagePull

### ISSUE THREAD

**Issue by jmbravo** [actions/runner-container-hooks#144]
Hi,

I have changed the containerMode from dind to Kubernetes.

The problem is that when I launch the workflow the newly created pod cannot pull the image, why can this happen?

It seems to be a DNS error. On the other hand, the "parent" pod has configured the secret regcred and in dind mode it was pulling without problem.

What could have happened so that in kubernetes mode it can't pull?

Thanks!

`  ----     ------   ----  ----     -------
  Normal   Pulling  24s   kubelet  Pulling image "artifactory.mycompany.com/cloudops-images/ubuntu-sqlplus:1.0"
  Warning  Failed   24s   kubelet  Failed to pull image "artifactory.mycompany.com/cloudops-images/ubuntu-sqlplus:1.0": failed to pull and unpack image "artifactory.mycompany.com/cloudops-images/ubuntu-sqlplus:1.0": failed to resolve reference "artifactory.mycompany.com/cloudops-images/ubuntu-sqlplus:1.0": failed to do request: Head "https://artifactory.mycompany.com/v2/cloudops-images/ubuntu-sqlplus/manifests/1.0": dial tcp: lookup artifactory.mycompany.com on 10.77.252.41:53: no such host
  Warning  Failed   24s   kubelet  Error: ErrImagePull
  Normal   BackOff  24s   kubelet  Back-off pulling image "artifactory.mycompany.com/cloudops-images/ubuntu-sqlplus:1.0"
  Warning  Failed   24s   kubelet  Error: ImagePullBackOff`
  
  
  Edit: my container registry has public IP so I need nameserver 8.8.8.8, I don't know why it's trying 10.77.252.41:53

**Comment by jmbravo** [comment]
Ok so it seems the workflow pod is not getting the docker credentials. The parent pod has a volume:

```
      volumeMounts:
        - mountPath: /home/runner/.docker/
          name: docker-secret
          readOnly: true
      volumes:
        - name: docker-secret
          secret:
            items:
              - key: .dockerconfigjson
                path: config.json
            secretName: regcred
```
But the workflow pod doesn't have it.

Is this normal?

**Comment by nikola-jokic** [comment]
Hey @jmbravo,

Please correct me if I'm wrong, but you should configure image pull secrets in this case. In container mode kubernetes, instead of using docker and running docker pull, we run a pod. So if you are using a private image for your pod, you would have to configure image pull secrets in order to allow kubernetes to pull the image properly. Can you please tell me how are you providing those credentials? If [credentials](https://github.com/actions/runner-container-hooks/blob/99efdeca9900ad616d7b8e35194633cf6753db26/examples/prepare-job.json#L62) are provided within a workflow, [the hook will set the `imagePullSecrets` field.](https://github.com/actions/runner-container-hooks/blob/99efdeca9900ad616d7b8e35194633cf6753db26/packages/k8s/src/k8s/index.ts#L117)

**Comment by jmbravo** [comment]
Hey @nikola-jokic, thanks for your response.

I tried two things with no luck:

1- Add
```

      imagePullSecrets:
        - name: regcred
```

to my RunnerDeployment

2 - Add 

```
imagePullSecrets:
 - name: regcred
image:
  actionsRunnerImagePullSecrets:
    - regcred
```

to Helm values.yml

What am I missing? 

Where am I suppose to add the imagePullSecrets so my workflow pod gets it?

This is my complete RunnerDeploymeny yml

```
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: arc-runner-cloudops-test
  namespace: runner
spec:
  template:
    metadata:
    spec:
      registry: artifactory.mycompany.com
      imagePullSecrets:
        - name: regcred
      tolerations:
      - key: node-pool
        effect: NoSchedule
        operator: Equal
        value: runner
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      dnsConfig:
          nameservers: 
            - 8.8.8.8
      containerMode: kubernetes
      serviceAccountName: default
      workVolumeClaimTemplate:
        storageClassName: "ebs-pool"
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi      
      volumeMounts:
        - mountPath: /home/runner/.docker/
          name: docker-secret
          readOnly: true 
      volumes:
        - name: docker-secret
          secret:
            items:
              - key: .dockerconfigjson
                path: config.json
            secretName: regcred
      organization: mycompany
      group: amazon-github-runners-cloudops-test
      labels:
        - arc-runner-cloudops-test
      env:
        - name: ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT
          value: "true"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_GRACEFUL_STOP_TIMEOUT
          value: "120"
      terminationGracePeriodSeconds: 180
      imagePullPolicy: IfNotPresent
```


Thank you!

**Comment by nikola-jokic** [comment]
Oh of course, happy to help! :relaxed: 

With the current setup, the hook will not be able to see the image pull secrets you specified. There are two ways you can do this:
1. Specify credentials in the workflow file. This way, credentials are going to be passed by the runner to the hook, and the hook will apply it to the new job pod
2. Use hook extensions. This approach is slightly harder to maintain, but it allows you to modify the hook behavior and the spec that is applied to the job pod. With the new release, the hook will be able to target service containers for these modifications as well :relaxed:. To configure it, please read the [ADR](https://github.com/actions/runner-container-hooks/blob/main/docs/adrs/0134-hook-extensions.md).

**Comment by jmbravo** [comment]
Thanks, that makes sense!

However, if I understood you correctly, you mean adding the credentials in the Github workflow. I have done that, but I still get the same error:


```
jobs:
  Getting-data-from-RDS:
    runs-on: arc-runner-cloudops-test
    container:
      image: artifactory.mycompany.com/cloudops-test/ubuntu-sqlplus:1.0
      credentials:
        username: $ARTIFACTORY_USER_TEST
        password: $ARTIFACTORY_PASSWORD_TEST
```

Did you mean this? Sorry, I've been like this for a couple of days now and I'm a bit blind.
