### ISSUE TITLE
How to use cleanup_job hook

### ISSUE THREAD

**Issue by aannara** [actions/runner-container-hooks#151]
I want to use the cleanup_job hook to upload the container as is to private registry after job is completed.
Am I expected to add this logic directly into "packages/docker/src/hooks/cleanup-job.ts"  and then build it?
Or is there a more appropriate place to do this?
I still want the normal cleanup activities to happen, I just want to add this step before any container cleanup happens

**Comment by nikola-jokic** [comment]
Hey @aannara,

You can do that by modifying the hook. However, depending on your requirements, I would prefer using a step that [always](https://docs.github.com/en/actions/learn-github-actions/expressions#always) execute. Again, not sure exactly if that would help you, if you can solve it with the workflow, you can avoid maintaining the hook yourself :relaxed:

**Comment by aannara** [comment]
> Hey @aannara,
> 
> You can do that by modifying the hook. However, depending on your requirements, I would prefer using a step that [always](https://docs.github.com/en/actions/learn-github-actions/expressions#always) execute. Again, not sure exactly if that would help you, if you can solve it with the workflow, you can avoid maintaining the hook yourself ☺️

Maybe I am missing the idea here. I want to push the actual container running the github actions to a registry. always is used with a step which is inside the container. Can I use always to the container itself ?

**Comment by aannara** [comment]
Let's say below is my workflow file:
```
jobs:
  job-name:
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    container:
      image: ubuntu:22.04
    steps:
      - name: Install system dependencies
        run: |
          apt update -y
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Python script
        run: python3 my_script.py
```
This workflow will trigger `Initialize containers` step which creates the container, then run each of my steps inside this container. Now I want this container, which contains "ubuntu + git checkout  + set python + python script" to be pushed to a repository.
Is this not possible by using the cleanup_job  hook? Or will the container still be vanilla ubuntu image?
