### ISSUE TITLE
Workflow fails to pull image from private registry due to missing authentication

### ISSUE THREAD

**Issue by diegoara96** [actions/runner-container-hooks#208]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
create a worflow that uses a service from a private repository as follows:

      postgresdb:
        # Docker Hub image
        image: my.private.registry/project/postgresdb:latest
        credentials:
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASS }}
```

### Describe the bug

When creating a workflow that needs to use images hosted in a private repository we see a “no basic auth credentials” error. The same workflow running against a normal self-hosted runner is able to download the image.

I opened this discussion #3741 thinking it was a question but seeing that with the normal self-runner it works I understand that it is a bug. 

### Describe the expected behavior

It should work just like a self-hosted runner and be able to download the image from the private registry.

### Additional Context

```yaml
githubConfigUrl: "URL"

githubConfigSecret:
  ### GitHub PAT Configuration
  github_token: "ghp_TOKEN"

## maxRunners is the max number of runners the autoscaling runner set will scale up to.
#maxRunners: 5

## minRunners is the min number of idle runners. The target number of runners created will be
## calculated as a sum of minRunners and the number of jobs assigned to the scale set.
minRunners: 1

containerMode:
  type: "kubernetes"  ## type can be set to dind or kubernetes
  kubernetesModeWorkVolumeClaim:
    accessModes: ["ReadWriteOnce"]
    storageClassName: "rook-cephfs"
    resources:
      requests:
        storage: 2Gi

  spec:
    securityContext:
      fsGroup: 1001
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
 #          - name: ACTIONS_RUNNER_CONTAINER_HOOKS
 #            value: /home/runner/k8s/index.js
 #          - name: ACTIONS_RUNNER_POD_NAME
 #            valueFrom:
 #              fieldRef:
 #                fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "false"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
      resources:
        requests:
          memory: "1Gi"
          cpu: "2"
        limits:
          memory: "4Gi"
          cpu: "4"
          
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "rook-cephfs"
              resources:
                requests:
                  storage: 2Gi
```

### Controller Logs

```shell
https://gist.github.com/diegoara96/20c6ce4fd17ef006de796bb1266b196d
```

### Runner Pod Logs

```shell
workflow describe: https://gist.github.com/diegoara96/e75fa18237a7643ecb71d34cce562bc9
runner log: https://gist.github.com/diegoara96/47a20be90c587594bf25605053642524
```

**Comment by ArieLevs** [comment]
Hi we are facing similar issue, both when using kubernetes or dind mode.
not only we cannot provide credentials using [Defining credentials for a container registry](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container#defining-credentials-for-a-container-registry)

we use EKS, so we don't even have a static token we can provide, each time a job runs it gets a short lived token to reach AWS resources (in my case ECR)

solving this issue on k8s level is pretty straightforward (image pull secrets/serviceaccount IRSA/etc)

what do we do in order to provide credential to this internal process? (running `aws ecr get-login-password ....`? where?)

**Comment by gitandre** [comment]
And this related to intermitent docker sock errors - not for this PR but still an issue as we are getting the same errors

https://github.com/actions/actions-runner-controller/discussions/2999

https://github.com/actions/actions-runner-controller/pull/3842

**Comment by ArieLevs** [comment]
> Hi we are facing similar issue, both when using kubernetes or dind mode. not only we cannot provide credentials using [Defining credentials for a container registry](https://docs.github.com/en/actions/writing-workflows/choosing-where-your-workflow-runs/running-jobs-in-a-container#defining-credentials-for-a-container-registry)
> 
> we use EKS, so we don't even have a static token we can provide, each time a job runs it gets a short lived token to reach AWS resources (in my case ECR)
> 
> solving this issue on k8s level is pretty straightforward (image pull secrets/serviceaccount IRSA/etc)
> 
> what do we do in order to provide credential to this internal process? (running `aws ecr get-login-password ....`? where?)

If anyone's interested I've solved this issue using [hook extensions](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#configuring-hook-extensions).  
Implementing a sidecar container (building images using Podman that needs to pull/pull from ecr) that executes `aws get-login ...` and shares the token via empty dir, it works but feels like a complex implementioan, would love to see GitHub arc to be more Kubernetes native

**Comment by copiousfreetime** [comment]
After lots of trial and error -- we have a solution that works for us -- most of this is **exactly** what I posted above... just with 1 particular yaml hierarchy change in the configMap:

## Working private container registry setup for workflows

This example uses cloudsmith -- any private container registry should work.

1. Create the`kubernetes.io/dockerconfigjson` type of secret in k8s: `cloudsmith-containers-auth`

2. Create a a configmap similar to the [example config map](https://docs.github.com/en/actions/tutorials/use-actions-runner-controller/deploy-runner-scale-sets#example-using-config-map-to-set-securitycontext)
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudsmith-containers-auth-hook-extension
  namespace: easypost-runner-scale-set
data:
  content: |
    metadata:
      annotations:
        cloudsmith-containers-auth: "enabled"
    spec:
      # This is the import bit -- imagePullSecrets goes just below spec -- not within `container`
      # This also means it works for all services in workflow files
      imagePullSecrets: 
      - name: cloudsmith-containers-auth
```

3. Update the scale set template :
```yaml
containerMode:
  type: 'kubernetes'
#...
template:
  spec:
    containers:
      - name: runner
         image: ghcr.io/actions/actions-runner:latest
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_CONTAINER_HOOKS
                value: /home/runner/k8s/index.js
              - name: ACTIONS_RUNNER_CONTAINER_HOOK_TEMPLATE
                value: /home/runner/_cloudsmith-containers-auth-extension/content
                #      ^ path from the volume mount
                #        basename is the key under `data` in the config map
              - name: ACTIONS_RUNNER_POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: cloudsmith-auth-hook-volume
                mountPath: /home/runner/_cloudsmith-containers-auth-extension
                readOnly: true
            volumes:
              - name: work
                ephemeral:
                  volumeClaimTemplate:
                    spec:
                      accessModes: [ "ReadWriteOnce" ]
                      storageClassName: "managed-premium"
                      resources:
                        requests:
                          storage: 10Gi
              - name: cloudsmith-auth-hook-volume
                configMap:
                  name: cloudsmith-containers-auth-hook-extension
```

5. Now our existing workflows work in private runners -- although the secrets are ignored in the workflow file when run on our runners.
```yaml
---
# ...
jobs:
  test:
    name: test-app
    # ....
    services:
      myservice:
        image: docker.cloudsmith.io/myorgname/containers/myservice:1.2.3
        credentials:
          username: ${{ secrets.CLOUDSMITH_GITHUB_CONTAINER_READ_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_GITHUB_CONTAINER_READ_API_KEY }}
        # ^ all of this is ignored by the k8s self hosted runners -- hence the whole need for the `imagePullSecrets`
```

**Comment by DamiAdesola** [comment]
Confirming this is registry-agnostic, not Harbor-specific -- hit the identical failure against **GHCR** under `containerMode: kubernetes` (controller 0.14.2, hooks matching that release):

```yaml
services:
  minio:
    image: ghcr.io/<org>/<private-image>:latest
    credentials:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
```

Job also had `permissions: { packages: read }`. Result on every attempt: the sidecar pull is
anonymous regardless -- ghcr.io returns `401 Unauthorized ... failed to fetch anonymous token`,
i.e. no basic auth is ever attempted, not even incorrectly. Same behavior whether or not
`credentials:` is present at all, which suggests the field is parsed but never wired into the
pod's pull path for `services:` containers specifically (the job's own `container:` image pulls
fine with ambient `GITHUB_TOKEN` auth -- this is scoped to sidecars).

Worth noting for anyone hitting this: there's no k8s-native workaround either if the credential
source is a workflow-scoped token (`GITHUB_TOKEN`) or a GitHub App installation token -- neither
can back a durable pod-template-level `imagePullSecret` (the former expires with the job, and App
installation tokens are not authorized for private ghcr package pulls at all, confirmed separately
against GHCR's access model). So this isn't just an inconvenience with a viable manual fallback for
ghcr private images -- it's a hard block short of making the image public or handing the runner a
long-lived PAT, which most orgs will (rightly) refuse to do in a runner-container's imagePullSecret.

Happy to share more repro detail if useful.
