### ISSUE TITLE
How to rollback to a previous version of runner-container-hooks?

### ISSUE THREAD

**Issue by zchenyu** [actions/runner-container-hooks#220]
I suspect there's a regression here: https://github.com/actions/runner-container-hooks/issues/201#issuecomment-2877605314

I want to test my theory by using an older release.

We're currently using ARC through Helm:
```
  - name: gha-controller      
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller
    namespace: gha-runners
    version: 0.9.3
  - name: gha-runner-h100
    chart: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
    namespace: gha-runners     
    version: 0.9.3
    values:                                    
      - ./helmfile-values.yaml
```

What's the recommended way of pinning to an older version of `runner-container-hooks` ?
