### ISSUE TITLE
Kubernetes mode terminating early or not terminating at all.

### ISSUE THREAD

**Issue by Josh-Engle** [actions/runner-container-hooks#228]
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.9.0

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
Create a workflow with a job that sleeps for 7 minutes and uses a ARC runner scale set configured in kubernetes mode.

Run the workflow.
```

### Describe the bug

Even if the workflow should have slept for 7 minutes, it completes successfully after 4 minutes OR it never completes.

Terminating Early:
![image](https://github.com/actions/runner-container-hooks/assets/87498771/c86ae284-ffbc-418d-bc1e-96bb78af07c3)

Never Terminating:
![image](https://github.com/actions/runner-container-hooks/assets/87498771/5c3fdef4-6449-4b01-876b-4ce7f8d67e5b)

### Describe the expected behavior

The workflow should have completed only after the sleep command completed.

### Additional Context

```yaml
values:
  - containerMode:
      kubernetesModeWorkVolumeClaim:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
        storageClassName: gh-runner-class
      type: kubernetes
    controllerServiceAccount:
      name: arc-gha-rs-controller
      namespace: arc-systems
    githubConfigSecret: sandbox
    githubConfigUrl: https://github.com/****
    githubServerTLS:
      certificateFrom:
        configMapKeyRef:
          key: ca.crt
          name: crt
      runnerMountPath: /usr/local/share/ca-certificates/
    maxRunners: 200
    minRunners: 5
    proxy:
      http:
        url: '*******'
      https:
        url: '*******'
      noProxy:
      - '*******'
      - '*******'
      - '*******'
      - '*******'
      - '*******'
    runnerGroup: preprod
    runnerScaleSetName: sandbox
    template:
      spec:
        containers:
        - command:
          - /home/runner/run.sh
          env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          image: ghcr.io/actions/actions-runner:latest
          name: runner
        securityContext:
          fsGroup: 123
```

### Controller Logs

```shell
[actions-runner-controller logs](https://gist.github.com/Josh-Engle/ea789d7eae1ca30e472fd90fba86bece)
```

### Runner Pod Logs

```shell
[Runner Pod Logs](https://gist.github.com/Josh-Engle/86fcca504a8c3175e87b1a1efbd3f794)

### kubectl describe output on job that never terminated.

Name:             ****************.k8s-qrp6d-runner-9f8xw
Namespace:        arc-runners
Priority:         0
Service Account:  *************.k8s-gha-rs-kube-mode
Node:             aks-runnerpool-35648369-vmss000015/10.139.31.13
Start Time:       Wed, 05 Jun 2024 11:48:26 -0700
Labels:           actions-ephemeral-runner=True
                  actions.github.com/organization=********************
                  actions.github.com/scale-set-name=****************
                  actions.github.com/scale-set-namespace=arc-runners
                  app.kubernetes.io/component=runner
                  app.kubernetes.io/part-of=gha-runner-scale-set
                  app.kubernetes.io/version=0.9.0
                  pod-template-hash=67bb8777b7
Annotations:      actions.github.com/patch-id: 70
                  actions.github.com/runner-group-name: *****************
                  actions.github.com/runner-scale-set-name: ******************
                  actions.github.com/runner-spec-hash: cdff6bcb
Status:           Running
IP:               10.244.0.76
IPs:
  IP:           10.244.0.76
Controlled By:  EphemeralRunner/*******************.k8s-qrp6d-runner-9f8xw
Containers:
  runner:
    Container ID:  containerd://71795364d03d6e29cc0a7d40623120040354ab416e7139528b39841c164d47f1
    Image:         ghcr.io/actions/actions-runner:latest
    Image ID:      ghcr.io/actions/actions-runner@sha256:95db6fbb020b9f734e8a00389291dae766f0e6ad3d1171ae2d68e9ad8ac4a985
    Port:          <none>
    Host Port:     <none>
    Command:
      /home/runner/run.sh
    State:          Running
      Started:      Wed, 05 Jun 2024 11:48:50 -0700
    Ready:          True
    Restart Count:  0
    Environment:
      ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER:    false
      ACTIONS_RUNNER_CONTAINER_HOOKS:          /home/runner/k8s/index.js
      ACTIONS_RUNNER_POD_NAME:                 *********************.k8s-qrp6d-runner-9f8xw (v1:metadata.name)
      NODE_EXTRA_CA_CERTS:                     /usr/local/share/ca-certificates/ca.crt
      RUNNER_UPDATE_CA_CERTS:                  1
      ACTIONS_RUNNER_INPUT_JITCONFIG:          <set to the key 'jitToken' in secret '*************.k8s-qrp6d-runner-9f8xw'>  Optional: false
      GITHUB_ACTIONS_RUNNER_EXTRA_USER_AGENT:  actions-runner-controller/0.9.0
      http_proxy:                              <set to the key 'http_proxy' in secret '*************.k8s-qrp6d-754b578d-runner-proxy'>   Optional: false
      https_proxy:                             <set to the key 'https_proxy' in secret '*************.k8s-qrp6d-754b578d-runner-proxy'>  Optional: false
      no_proxy:                                <set to the key 'no_proxy' in secret '*************.k8s-qrp6d-754b578d-runner-proxy'>     Optional: false
    Mounts:
      /home/runner/_work from work (rw)
      /usr/local/share/ca-certificates/ca.crt from github-server-tls-cert (rw,path="ca.crt")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-c6wc6 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  github-server-tls-cert:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      crt
    Optional:  false
  work:
    Type:          EphemeralVolume (an inline specification for a volume that gets created and deleted with the pod)
    StorageClass:  gh-runner-class
    Volume:        
    Labels:            <none>
    Annotations:       <none>
    Capacity:      
    Access Modes:  
    VolumeMode:    Filesystem
  kube-api-access-c6wc6:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```
```

**Comment by LeonoreMangold** [comment]
@c-fteixeira I'm not sure `konnectivity-agent` is the (only ?) root cause of the problem. I digged into the issue on my own AKS cluster and found out that early terminations in workflows run by ARC Kubernetes mode's runners didn't coincide neither with scale up/down activities nor with `konnectivity-agent` pods being moved to other nodes.

I think the cause should be searched elsewhere. 
I also noticed than when the problem occurs, all active runners of the concerned runnerset are impacted at the same time.

**Comment by vvanouytsel** [comment]
Are there any more pointers on this issue?

@nikola-jokic , could we somehow increase the priority of this? We are also seeing this in our setup and it basically makes the entire CI system useless because you can't trust it.

Imagine that you have long running tests and the failing tests would occur after those 6 minutes, your CI would finish the job as successful and potentially release/deploy a broken artifact.

I would be happy to help troubleshoot this issue, but I don't immediately know where to start.

**Comment by nikola-jokic** [comment]
Hey @vvanouytsel 

I think this is cluster specific but I cannot confirm. Try looking at the kubelet log or similar. I'm happy to prioritize it but I'm failing to reproduce the issue. My guess is that the exec api fails but again, not sure...

**Comment by LeonoreMangold** [comment]
@nikola-jokic I provided some logs in [this linked issue](https://github.com/actions/runner-container-hooks/issues/165). As of now I don't have any clue to locate the root cause of the problem.

What was your setup to try reproducing the issue ?
Same question @vvanouytsel ?

**Comment by c-fteixeira** [comment]
I did not have time to explore, and js isn't my thing, but the latest lead i was chasing was [here](https://github.com/actions/runner-container-hooks/blob/v0.8.0/packages/k8s/src/k8s/index.ts#L245-L246) where the podexec doesn't handle the websocket returned by the library exec command. 

The theory of why the error scenarios are either indefinite hang or success is based on what that promise ended up getting from the stream when it failed..

**Comment by vvanouytsel** [comment]
Below is the setup I am using the replicate this issue.
I am running on AKS with Kubernetes version `1.33.5`.

This is the simple workflow I am using.

```yaml
name: Sleep bug
on: 
  workflow_dispatch:
jobs:
  job1:
    name: Upstream
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "This is executed"
          sleep 100000
          echo "This will not get executed"
          echo "Which is a problem, because it should fail."
          exit 1   
```

Version `0.13.1` of the scale set chart is used.

```sh
 ❯ helm ls -n gha-runner-scale-sets                  
NAME              	NAMESPACE            	REVISION	UPDATED                                	STATUS  	CHART                      	APP VERSION
upstream          	gha-runner-scale-sets	3       	2026-02-02 10:44:39.134137222 +0000 UTC	deployed	gha-runner-scale-set-0.13.1	0.13.1
```

This is the spec I pass via values to the Helm chart.
Based on https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml.
```yaml
template:
  spec:
    securityContext:
      fsGroup: 1001 # https://docs.github.com/en/actions/tutorials/use-actions-runner-controller/troubleshoot#error-access-to-the-path-homerunner_work_tool-is-denied
    serviceAccountName: my-serviceaccount
    containers:
    - name: runner
      image: ghcr.io/actions/actions-runner:latest
      command: ["/home/runner/run.sh"]
      env:
        - name: ACTIONS_RUNNER_CONTAINER_HOOKS
          value: /home/runner/k8s/index.js
        - name: ACTIONS_RUNNER_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
          value: "true"
      volumeMounts:
        - name: work
          mountPath: /home/runner/_work
    volumes:
      - name: work
        ephemeral:
          volumeClaimTemplate:
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "managed-csi-premium"
              resources:
                requests:
                  storage: 10Gi
```

As you can see, after around 5 minutes the job 'succeeds', while it should not do that.
<img width="335" height="197" alt="Image" src="https://github.com/user-attachments/assets/b1a29587-6660-4aa4-b66a-4d459d8a304e" />

@nikola-jokic could you attempt to reproduce this on your end and let me know if you were able to do so or not?
It seems people are hitting this on GKE and AKS as well. Can you also let me know what your test setup is like in case you cannot reproduce it?

I am just trying to find some patterns at this point to see where I can troubleshoot further.

**Comment by vvanouytsel** [comment]
I could not find anything special in the kubelet logs. The API sends a request to clean up the workflow pod and the kubelet obeys.

However I did find some pointers to WebSockets.
In Kubernetes 1.31 they have changed the protocol from SPDY to WebSockets.
https://kubernetes.io/blog/2024/08/20/websockets-transition/

Below is the same workflow as before, but extended with some extra test-cases to showcase the issue.

```yaml
name: Sleep bug
on: 
  workflow_dispatch:
jobs:
  job1:
    name: Upstream
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "This is executed"
          sleep 100000
          echo "This will not get executed"
          echo "Which is a problem, because it should fail."
          exit 1   

  job2:
    name: Long sleep with echo
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Sleep in loop
        shell: bash
        run: |
          echo "Starting 500 iterations of 60-second sleeps (total: 500 minutes)"
          for i in {1..500}; do
            echo "Iteration $i/500 - sleeping for 60 seconds..."
            sleep 60
            echo "Iteration $i/500 completed"
          done
          echo "All 500 iterations completed!"


  job3:
    name: Long sleep without echo
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Sleep in loop
        shell: bash
        run: |
          for i in {1..500}; do
            sleep 60
          done
```


`job2` and `job3` are identical, the only difference is that `job2` contains some echo statements.
If we look at the results, we can see that `job2` keeps running, as we expect. I expect this is the case because the logging prevents the websocket from closing. As soon as no data is send for 5 minutes on the websocket, the websocket closes and the 'bug' occurs.

<img width="380" height="309" alt="Image" src="https://github.com/user-attachments/assets/fadafcc7-768c-40ef-b098-db3b910789db" />

However, that also means that this issue is cloud-agnostic and thus you should be able to replicate it on your side (as long as you are using Kubernetes v1.31 or later).

**Comment by vvanouytsel** [comment]
> [@c-fteixeira](https://github.com/c-fteixeira) I'm not sure `konnectivity-agent` is the (only ?) root cause of the problem. I digged into the issue on my own AKS cluster and found out that early terminations in workflows run by ARC Kubernetes mode's runners didn't coincide neither with scale up/down activities nor with `konnectivity-agent` pods being moved to other nodes.
> 
> I think the cause should be searched elsewhere. I also noticed than when the problem occurs, all active runners of the concerned runnerset are impacted at the same time.

@LeonoreMangold, In our case there is no link between this bug and any other runners of the runnerset. I tested this and as you can see from the results, each runner stops with exit code 0 after 5 minutes of no received output.

```yml
name: Sleep bug
on: 
  workflow_dispatch:
jobs:
  job1:
    name: Upstream
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "This is executed"
          sleep 100000
          echo "This will not get executed"
          echo "Which is a problem, because it should fail."
          exit 1  
  
  job1_duplicate:
    name: Upstream-duplicate
    runs-on: upstream
    container:
      image: ubuntu:24.04
    steps:
      - name: Step 0
        id: step0
        run: |
          echo "Some user claimed that all runners in the same runnerset are impacted if the bug occurs."
          echo "Let's wait 3 minutes before we start the 5m countdown to trigger the bug, I don't expect this runner to be killed at the same time as the runner in the 'upstream' job."
          echo "I expect there will be a 3 minute difference, introduced by the sleep on the next line."
          sleep 180

      - name: Step 1
        id: step1
        run: |
          echo "This is executed"
          sleep 100000
          echo "This will not get executed"
          echo "Which is a problem, because it should fail."
          exit 1   
```

<img width="425" height="270" alt="Image" src="https://github.com/user-attachments/assets/1c7b1ef1-afd7-4880-b5b4-4ad71c91905a" />

**Comment by vvanouytsel** [comment]
I have had a look in the Kubernetes API Audit logs in our AKS cluster.

* At 10:38 the workflow pod is created by the runner pod in the API.
* The scheduler selects a node and the kubelet of that node starts the container
* The content of the workflow is executed (sleep 99999 in our case)
* At 10:43, 5 minutes later (which is when the bug occurs) the runner pod calls the exec API to exec in the `job` container of the `xxx-workflow` pod. This API call returns a `101` response which means '[Switching Protocols](https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status/101)'
```
/api/v1/namespaces/gha-runner-scale-sets/pods/upstream-vwk76-runner-mbh8r-workflow/exec?stdout=true&stderr=true&stdin=false&tty=false&command=sh&command=-e&command=%2F__w%2F_temp%2Fa32ade40-01b5-11f1-a5d2-97394121df3c.sh&container=job
```
* One second later, the runner pod calls the DELETE endpoint on the API to delete the workflow pod.
* The kubelet stops and removes the container.


I don't know if the `exec` call to the API after 5 minutes is the cause of the issue, or is normal behavior where the runner pod is collecting some logs from the workflow pod.

@nikola-jokic , perhaps you can answer that?



<img width="2227" height="687" alt="Image" src="https://github.com/user-attachments/assets/fc65f556-1d81-4748-9a2c-99d65f6c5812" />

**Comment by vvanouytsel** [comment]
Another interested thing to note is that I attempted to replicate this issue using `kubectl`, but I was not able to do so.
However, I did notice that there is a hearbeat mechanism in plate that prevents the websocket for closing, as you can see in the logs below.

Could it be that for some reason the implementation in `runner-container-hooks` is not using that heartbeat mechanism?


```
❯ date ; kubectl exec -ti -v=8 -n gha-runner-scale-sets upstream-xpfk2-runner-rctvg -- /usr/bin/sleep 999999
Thu Feb  5 03:26:54 PM CET 2026

I0205 15:26:54.889713 355090 loader.go:395] Config loaded from file: /home/vvanouytsel/.kube/config

I0205 15:26:54.892755 355090 round_trippers.go:463] GET https://redacted:443/api/v1/namespaces/gha-runner-scale-sets/pods/upstream-xpfk2-runner-rctvg
I0205 15:26:54.892766 355090 round_trippers.go:469] Request Headers:
I0205 15:26:54.892778 355090 round_trippers.go:473]     Accept: application/json, */*
I0205 15:26:54.892781 355090 round_trippers.go:473]     User-Agent: kubectl/v1.31.0 (linux/amd64) kubernetes/9edcffc

I0205 15:26:55.298923 355090 round_trippers.go:574] Response Status: 200 OK in 406 milliseconds
I0205 15:26:55.298992 355090 round_trippers.go:577] Response Headers:
I0205 15:26:55.299015 355090 round_trippers.go:580]     X-Kubernetes-Pf-Prioritylevel-Uid: da74fc6a-a9da-4ad8-bf8a-46fa2b6bac83
I0205 15:26:55.299029 355090 round_trippers.go:580]     Date: Thu, 05 Feb 2026 14:26:55 GMT
I0205 15:26:55.299038 355090 round_trippers.go:580]     Audit-Id: 41c2dd0e-4f86-46b8-9263-6d023f53546e
I0205 15:26:55.299050 355090 round_trippers.go:580]     Cache-Control: no-cache, private
I0205 15:26:55.299059 355090 round_trippers.go:580]     Content-Type: application/json
I0205 15:26:55.299067 355090 round_trippers.go:580]     X-Kubernetes-Pf-Flowschema-Uid: 8cf56144-1d95-4d0d-a81d-e4917449d94c

I0205 15:26:55.299293 355090 request.go:1351] Response Body:
{"kind":"Pod","apiVersion":"v1","metadata":{"name":"upstream-xpfk2-runner-rctvg","namespace":"gha-runner-scale-sets","uid":"566ac6c8-a9c3-4699-ac58-8543550f3b98","resourceVersion":"126005434","generation":1,"creationTimestamp":"2026-02-05T13:35:53Z","labels":{"actions-ephemeral-runner":"True","actions.github.com/organization":"TrendMiner","actions.github.com/scale-set-name":"upstream","actions.github.com/scale-set-namespace":"gha-runner-scale-sets","app.kubernetes.io/component":"runner","app.kubernetes.io/instance":"upstream","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"upstream","app.kubernetes.io/part-of":"gha-runner-scale-set","app.kubernetes.io/version":"0.13.1","helm.sh/chart":"gha-rs-0.13.1","pod-template-hash":"6745fb8d7c"},"annotations":{"actions.github.com/patch-id":"1860","actions.github.com/runner-group-name":"Default","actions.github.com/runner-scale-set-name":"upstream","actions.github.com/runner-spec-hash":"78cc599c5d"},"ownerReferences":[{"apiVersion":"actions.github.com/v1al [truncated 7108 chars]

I0205 15:26:55.303859 355090 podcmd.go:88] Defaulting container name to runner

I0205 15:26:55.304557 355090 round_trippers.go:463] GET https://redacted:443/api/v1/namespaces/gha-runner-scale-sets/pods/upstream-xpfk2-runner-rctvg/exec?command=%2Fusr%2Fbin%2Fsleep&command=999999&container=runner&stdin=true&stdout=true&tty=true
I0205 15:26:55.304582 355090 round_trippers.go:469] Request Headers:
I0205 15:26:55.304606 355090 round_trippers.go:473]     Sec-Websocket-Protocol: v5.channel.k8s.io
I0205 15:26:55.304614 355090 round_trippers.go:473]     User-Agent: kubectl/v1.31.0 (linux/amd64) kubernetes/9edcffc

I0205 15:26:55.495888 355090 round_trippers.go:574] Response Status: 101 Switching Protocols in 191 milliseconds
I0205 15:26:55.495951 355090 round_trippers.go:577] Response Headers:
I0205 15:26:55.495970 355090 round_trippers.go:580]     Upgrade: websocket
I0205 15:26:55.495981 355090 round_trippers.go:580]     Connection: Upgrade
I0205 15:26:55.495990 355090 round_trippers.go:580]     Sec-Websocket-Accept: REDACTED=
I0205 15:26:55.495997 355090 round_trippers.go:580]     Sec-Websocket-Protocol: v5.channel.k8s.io
I0205 15:26:55.496004 355090 round_trippers.go:580]     Date: Thu, 05 Feb 2026 14:26:55 GMT

I0205 15:26:55.496020 355090 websocket.go:133] The subprotocol is v5.channel.k8s.io
I0205 15:26:55.496282 355090 websocket.go:357] Write() on stream 4
I0205 15:26:55.496469 355090 websocket.go:390] Write() done on stream 4

I0205 15:27:00.497219 355090 websocket.go:497] Websocket Ping succeeeded
I0205 15:27:00.555117 355090 websocket.go:455] Pong message received ()--resetting read deadline
I0205 15:27:05.496969 355090 websocket.go:497] Websocket Ping succeeeded
I0205 15:27:05.511260 355090 websocket.go:455] Pong message received ()--resetting read deadline
I0205 15:27:10.497199 355090 websocket.go:497] Websocket Ping succeeeded
I0205 15:27:10.510768 355090 websocket.go:455] Pong message received ()--resetting read deadline
I0205 15:27:14.867695 355090 websocket.go:357] Write() on stream 4
I0205 15:27:14.867765 355090 websocket.go:390] Write() done on stream 4
I0205 15:27:15.278214 355090 websocket.go:357] Write() on stream 4
I0205 15:27:15.278297 355090 websocket.go:390] Write() done on stream 4
```

**Comment by vvanouytsel** [comment]
I managed to resolve this issue by implementing a heartbeat mechanism whenever websockets are used. This makes sure that the read deadline is constantly reset even if no output is received.

```yaml
name: Sleep bug
on: 
  workflow_dispatch:
jobs:
  job1:
    name: Staging
    runs-on: default-staging
    container:
      image: ubuntu:24.04
    steps:
      - name: Step 1
        id: step1
        run: |
          echo "This is executed"
          sleep 100000
          echo "This will not get executed"
          echo "Which is a problem, because it should fail."
          exit 1  
```

Above is the workflow that I tested with, and as you can see, it no longer stops after 5 minutes with exit code 0.


<img width="343" height="199" alt="Image" src="https://github.com/user-attachments/assets/c01ff66c-f671-4113-b43e-9e227b38dac9" />

I am currently running my own fork, but ideally this would get merged and released as `v0.7.1`. Though I don't see any release branch for v0.7.0 so I am not sure how to create a PR to introduce my changes upstream.

The changes I did to make this work can be found [here](https://github.com/vvanouytsel-trendminer/runner-container-hooks/commit/e7d51bac26b857755acc9182cf3f04676d004174).

How should I continue with this @nikola-jokic ?
