### ISSUE TITLE
k8s hook: equal signs (=) in environment vars  are escaped in job pods

### ISSUE THREAD

**Issue by syslxg** [actions/runner-container-hooks#61]
while using k8s container mode with ARC, I found 'google-github-actions/auth@v1'  action stopped working and the problem was '=' in base64 strings were escaped ('\\=') and that broke the JSON parsing.

the following workflow can show this problem.

```yaml
name: K8S runner env issue
env:
  foo: '{"user": "YWJjCg=="}'
on:
  workflow_dispatch:
jobs:
  envissue:
    runs-on: k8s
    container:
      image: ubuntu
    steps:
    - run: |
        apt-get update
        apt-get install -y jq
        echo "foo: $foo"        
        echo "$foo" | jq -r .user

```
This workflow will fail on k8s runners (with k8s hook)
Actual output is :

```
foo: {"user": "YWJjCg\=\="}
parse error: Invalid escape at line 1, column 21
```

expected output is:

```
foo: {"user": "YWJjCg=="}
YWJjCg==
```
